language: java
sudo: false
services:
  - mysql
before_script:
  - mysql -e 'create database justjournal_test;'
  - mysql --database=justjournal_test < database/jj_create.sql
  - mysql --database=justjournal_test < database/jj_data_load.sql
