language: java
dist: bionic
jdk:
  - openjdk9
  - openjdk11
node_js: "4"
services:
  - mysql
  - elasticsearch
before_script:
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash"
  - mysql -e 'create database justjournal_test;'
  - mysql --database=justjournal_test < src/main/resources/db/migration/V1_0__jj_create.sql
  - mysql --database=justjournal_test < database/jj_data_load.sql
script:
  - fossa init
  - fossa analyze