language: java
dist: bionic
jdk:
  - openjdk9
  - openjdk11
node_js: "4"
services:
  - mysql
  - elasticsearch
  - redis
before_script:
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash"
  - mysql -e 'create database justjournal_test;'
  - mysql --database=justjournal_test < src/main/resources/db/migration/V1_0__jj_create.sql
  - mysql --database=justjournal_test < database/jj_data_load.sql
addons:
      sonarcloud:
        organization: "laffer1-github"
        token:
          secure: "uHQJcIboihtqZoLIIsyQyaRJbzERa2tOyKNLgRkCzxO1/qKUUnm2xc3zPfTc/aFjj/zZO0rXX15Ri9JKLtB4dfELEL5q4J2bulVbdHdm2DFSHQNpAY8SKLnY4jZ5+t+JoJMPNX09mWd4FVDkj9EhZpsLmtHiECF4P+9xH03bJJ4="
script:
  - fossa init
  - fossa analyze
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=com.justjournal:justjournal