spring:
  profiles.default: default
---
spring:
  config:
    activate:
      on-profile: default
  application:
    name: justjournal
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: true
  flyway:
    baseline-on-migrate: true
    table: schema_version
  jackson:
    serialization:
      write-dates-as-timestamps: false
  elasticsearch:
    uris: http://localhost:9200
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/jj
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jj
    password: 
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 30
      minimum-idle: 2
      idle-timeout: 14400
      max-lifetime: 14400
      connection-timeout: 30000
      pool-name: JJHikariCP
      connection-test-query: SELECT 1
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
     dialect: org.hibernate.dialect.MySQLDialect
     physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     hibernate:
       temp:
         use_jdbc_metadata_defaults: false
     jakarta:
       persistence:
         sharedCache:
           mode: ALL
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
  cache:
    type: redis
  web:
    resources:
      static-locations: classpath:/static/
  data:
    redis:
      port: 6379
      host: localhost

server:
  port: ${port:8200}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

app:
  minio:
    host: http://ds9.midnightbsd.org:9000/
    accessKey:
    secretKey:

bucket:
  avatar: jjavatar
  image: jjimages

bing:
  indexNowKey:

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      filter-method: servlet
      filter-order: 1
      url: .*
      metrics:
        tags:
          - key: IP
            expression: getRemoteAddr()
            types: REJECTED_COUNTER
          - key: URL
            expression: getRequestURI()
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 10
              time: 10
              unit: seconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
  info:
    git:
      mode: full

---
spring:
  config:
    activate:
      on-profile: test
  elasticsearch:
    uris: http://localhost:9200
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/justjournal_test
    type: com.zaxxer.hikari.HikariDataSource
    username: travis
    password:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/justjournal_test
      maximum-pool-size: 10
      minimum-idle: 1
      max-lifetime: 14400
      idle-timeout: 14400
  flyway:
    baseline-on-migrate: true
    table: schema_version

app:
  minio:
    host: http://localhost:9000/
    accessKey: test
    secretKey: test

bucket:
  avatar: jjqaavatar
  image: jjqaimages

bing:
  indexNowKey:

---
spring:
  config:
    activate:
      on-profile: it
  elasticsearch:
    uris: http://localhost:9200
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/justjournal_test
    type: com.zaxxer.hikari.HikariDataSource
    username: travis
    password:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/justjournal_test
      maximum-pool-size: 10
      minimum-idle: 1
      max-lifetime: 14400
      idle-timeout: 14400
  flyway:
    baseline-on-migrate: true
    table: schema_version

app:
  minio:
    host: http://localhost:9000/
    accessKey: test
    secretKey: test

bucket:
  avatar: jjqaavatar
  image: jjqaimages

bing:
  indexNowKey: