spring:
  profiles.default: default
---
spring:
  config:
    activate:
      on-profile: default
  flyway:
    baseline-on-migrate: true
    table: schema_version
  jackson:
    serialization:
      write-dates-as-timestamps: false
  elasticsearch:
    uris: http://localhost:9200
  datasource:
    url: jdbc:mysql://localhost:3306/jj
    driver-class-name: com.mysql.jdbc.Driver
    username: jj
    password: 
    max-active: 30
    initial-size: 5
    max-idle: 5
    min-idle: 2
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 30
      minimum-idle: 2
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: false
    show-sql: false
    properties:
     dialect: org.hibernate.dialect.MySQL5Dialect
     hibernate:
       temp:
         use_jdbc_metadata_defaults: false
     javax:
       persistence:
         sharedCache:
           mode: ALL
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    serviceUrl:
     defaultZone: http://127.0.0.1:8761/eureka/

app:
  minio:
    host: http://ds9.midnightbsd.org:9000/
    accessKey:
    secretKey:

bucket:
  avatar: jjavatar
  image: jjimages

---
spring:
  config:
    activate:
      on-profile: test
  elasticsearch:
    uris: http://localhost:9200
  datasource:
    url: jdbc:mysql://localhost:3306/justjournal_test
    username: travis
    password:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/justjournal_test
      maximum-pool-size: 10
      minimum-idle: 1
  flyway:
    baseline-on-migrate: true
    table: schema_version

app:
  minio:
    host: http://localhost:9000/
    accessKey: test
    secretKey: test

bucket:
  avatar: jjqaavatar
  image: jjqaimages
